export type ICountry = {
  name: string;
  iso2: string;
  capital: string;
  coordinates: {
    latitude: number;
    longitude: number;
  };
  continent: string;
  isPopular: boolean;
};
export const CountriesList = [
  {
    name: "Afghanistan",
    iso2: "AF",
    capital: "Kabul",
    coordinates: {
      latitude: 34.094326,
      longitude: 66.36995,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Albania",
    iso2: "AL",
    capital: "Tirana",
    coordinates: {
      latitude: 41.100988,
      longitude: 20.047248,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Algeria",
    iso2: "DZ",
    capital: "Algiers",
    coordinates: {
      latitude: 28.884561,
      longitude: 2.59381,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Andorra",
    iso2: "AD",
    capital: "Andorra la Vella",
    coordinates: {
      latitude: 42.545442,
      longitude: 1.58223,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Angola",
    iso2: "AO",
    capital: "Luanda",
    coordinates: {
      latitude: -12.04932,
      longitude: 17.557906,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Antigua and Barbuda",
    iso2: "AG",
    capital: "St. John's",
    coordinates: {
      latitude: 17.081245,
      longitude: -61.792794,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Argentina",
    iso2: "AR",
    capital: "Buenos Aires",
    coordinates: {
      latitude: -36.151477,
      longitude: -65.063029,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Armenia",
    iso2: "AM",
    capital: "Yerevan",
    coordinates: {
      latitude: 40.249513,
      longitude: 44.947493,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Australia",
    iso2: "AU",
    capital: "Canberra",
    coordinates: {
      latitude: -26.942005,
      longitude: 134.000674,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Austria",
    iso2: "AT",
    capital: "Vienna",
    coordinates: {
      latitude: 47.679989,
      longitude: 14.947254,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Azerbaijan",
    iso2: "AZ",
    capital: "Baku",
    coordinates: {
      latitude: 40.522872,
      longitude: 47.454745,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Bahamas",
    iso2: "BS",
    capital: "Nassau",
    coordinates: {
      latitude: 24.461562,
      longitude: -77.97063,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Bahrain",
    iso2: "BH",
    capital: "Manama",
    coordinates: {
      latitude: 26.067706,
      longitude: 50.553182,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Bangladesh",
    iso2: "BD",
    capital: "Dhaka",
    coordinates: {
      latitude: 24.017356,
      longitude: 90.120178,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Barbados",
    iso2: "BB",
    capital: "Bridgetown",
    coordinates: {
      latitude: 13.158707,
      longitude: -59.551065,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Belarus",
    iso2: "BY",
    capital: "Minsk",
    coordinates: {
      latitude: 53.77244,
      longitude: 28.38226,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Belgium",
    iso2: "BE",
    capital: "Brussels",
    coordinates: {
      latitude: 50.594809,
      longitude: 4.965363,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Belize",
    iso2: "BZ",
    capital: "Belmopan",
    coordinates: {
      latitude: 17.207783,
      longitude: -88.642324,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Benin",
    iso2: "BJ",
    capital: "Porto-Novo",
    coordinates: {
      latitude: 9.514418,
      longitude: 2.348253,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Bhutan",
    iso2: "BT",
    capital: "Thimphu",
    coordinates: {
      latitude: 27.356131,
      longitude: 90.505782,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Bolivia",
    iso2: "BO",
    capital: "La Paz",
    coordinates: {
      latitude: -17.12273,
      longitude: -64.164394,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Bosnia and Herzegovina",
    iso2: "BA",
    capital: "Sarajevo",
    coordinates: {
      latitude: 44.169023,
      longitude: 17.911672,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Botswana",
    iso2: "BW",
    capital: "Gaborone",
    coordinates: {
      latitude: -22.520968,
      longitude: 23.920464,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Brazil",
    iso2: "BR",
    capital: "Brasília",
    coordinates: {
      latitude: -9.542167,
      longitude: -51.405148,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Brunei",
    iso2: "BN",
    capital: "Bandar Seri Begawan",
    coordinates: {
      latitude: 4.465042,
      longitude: 114.623528,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Bulgaria",
    iso2: "BG",
    capital: "Sofia",
    coordinates: {
      latitude: 42.638517,
      longitude: 25.100905,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Burkina Faso",
    iso2: "BF",
    capital: "Ouagadougou",
    coordinates: {
      latitude: 12.148733,
      longitude: -1.603375,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Burundi",
    iso2: "BI",
    capital: "Bujumbura",
    coordinates: {
      latitude: -3.356403,
      longitude: 29.930471,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Cape Verde",
    iso2: "CV",
    capital: "Praia",
    coordinates: {
      latitude: 15.06909,
      longitude: -23.625341,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Cambodia",
    iso2: "KH",
    capital: "Phnom Penh",
    coordinates: {
      latitude: 12.551487,
      longitude: 104.942664,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Cameroon",
    iso2: "CM",
    capital: "Yaoundé",
    coordinates: {
      latitude: 5.027609,
      longitude: 12.676266,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Canada",
    iso2: "CA",
    capital: "Ottawa",
    coordinates: {
      latitude: 59.382377,
      longitude: -105.963188,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Central African Republic",
    iso2: "CF",
    capital: "Bangui",
    coordinates: {
      latitude: 6.614337,
      longitude: 19.176645,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Chad",
    iso2: "TD",
    capital: "N'Djamena",
    coordinates: {
      latitude: 15.278935,
      longitude: 18.338907,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Chile",
    iso2: "CL",
    capital: "Santiago",
    coordinates: {
      latitude: -33.830983,
      longitude: -70.962921,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "China",
    iso2: "CN",
    capital: "Beijing",
    coordinates: {
      latitude: 33.362313,
      longitude: 103.722585,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Colombia",
    iso2: "CO",
    capital: "Bogotá",
    coordinates: {
      latitude: 4.17106,
      longitude: -73.193937,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Comoros",
    iso2: "KM",
    capital: "Moroni",
    coordinates: {
      latitude: -11.732913,
      longitude: 43.353157,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Congo (Congo-Brazzaville)",
    iso2: "CG",
    capital: "Brazzaville",
    coordinates: {
      latitude: -1.460205,
      longitude: 15.694773,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Costa Rica",
    iso2: "CR",
    capital: "San José",
    coordinates: {
      latitude: 9.921901,
      longitude: -84.011738,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Croatia",
    iso2: "HR",
    capital: "Zagreb",
    coordinates: {
      latitude: 45.335007,
      longitude: 15.546456,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Cuba",
    iso2: "CU",
    capital: "Havana",
    coordinates: {
      latitude: 21.892606,
      longitude: -78.765576,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Cyprus",
    iso2: "CY",
    capital: "Nicosia",
    coordinates: {
      latitude: 35.007444,
      longitude: 33.213489,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Ivory Coast",
    iso2: "CI",
    capital: "Yamoussoukro",
    coordinates: {
      latitude: 7.872419,
      longitude: -5.596598,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Czechia",
    iso2: "CZ",
    capital: "Prague",
    coordinates: {
      latitude: 49.773794,
      longitude: 15.604534,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "DR of the Congo",
    iso2: "CD",
    capital: "Kinshasa",
    coordinates: {
      latitude: -1.857246,
      longitude: 23.490572,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Denmark",
    iso2: "DK",
    capital: "Copenhagen",
    coordinates: {
      latitude: 56.005939,
      longitude: 9.53045,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Djibouti",
    iso2: "DJ",
    capital: "Djibouti",
    coordinates: {
      latitude: 11.540902,
      longitude: 42.481531,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Dominica",
    iso2: "DM",
    capital: "Roseau",
    coordinates: {
      latitude: 15.424327,
      longitude: -61.335549,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Dominican Republic",
    iso2: "DO",
    capital: "Santo Domingo",
    coordinates: {
      latitude: 18.79535,
      longitude: -70.268483,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Ecuador",
    iso2: "EC",
    capital: "Quito",
    coordinates: {
      latitude: 1.683958,
      longitude: -78.624537,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Egypt",
    iso2: "EG",
    capital: "Cairo",
    coordinates: {
      latitude: 26.059897,
      longitude: 29.942822,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "El Salvador",
    iso2: "SV",
    capital: "San Salvador",
    coordinates: {
      latitude: 13.705413,
      longitude: -88.86735,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Equatorial Guinea",
    iso2: "GQ",
    capital: "Malabo",
    coordinates: {
      latitude: 1.54228,
      longitude: 10.408889,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Eritrea",
    iso2: "ER",
    capital: "Asmara",
    coordinates: {
      latitude: 15.331173,
      longitude: 39.223143,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Estonia",
    iso2: "EE",
    capital: "Tallinn",
    coordinates: {
      latitude: 58.615026,
      longitude: 25.721836,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Eswatini (Swaziland)",
    iso2: "SZ",
    capital: "Mbabane",
    coordinates: {
      latitude: -26.518602,
      longitude: 31.558669,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Ethiopia",
    iso2: "ET",
    capital: "Addis Ababa",
    coordinates: {
      latitude: 9.045699,
      longitude: 40.453537,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Fiji",
    iso2: "FJ",
    capital: "Suva",
    coordinates: {
      latitude: -17.915115,
      longitude: 177.945028,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Finland",
    iso2: "FI",
    capital: "Helsinki",
    coordinates: {
      latitude: 64.74922,
      longitude: 27.072522,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "France",
    iso2: "FR",
    capital: "Paris",
    coordinates: {
      latitude: 47.077177,
      longitude: 2.582812,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Gabon",
    iso2: "GA",
    capital: "Libreville",
    coordinates: {
      latitude: -0.329531,
      longitude: 11.908262,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Gambia",
    iso2: "GM",
    capital: "Banjul",
    coordinates: {
      latitude: 13.516418,
      longitude: -15.390282,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Georgia",
    iso2: "GE",
    capital: "Tbilisi",
    coordinates: {
      latitude: 42.038068,
      longitude: 43.805146,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Germany",
    iso2: "DE",
    capital: "Berlin",
    coordinates: {
      latitude: 51.277277,
      longitude: 10.38294,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Ghana",
    iso2: "GH",
    capital: "Accra",
    coordinates: {
      latitude: 7.732915,
      longitude: -1.167342,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Greece",
    iso2: "GR",
    capital: "Athens",
    coordinates: {
      latitude: 39.262852,
      longitude: 22.004435,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Grenada",
    iso2: "GD",
    capital: "St. George's",
    coordinates: {
      latitude: 12.107919,
      longitude: -61.679631,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Guatemala",
    iso2: "GT",
    capital: "Guatemala City",
    coordinates: {
      latitude: 15.463587,
      longitude: -90.288458,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Guinea",
    iso2: "GN",
    capital: "Conakry",
    coordinates: {
      latitude: 10.765545,
      longitude: -10.717911,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Guinea-Bissau",
    iso2: "GW",
    capital: "Bissau",
    coordinates: {
      latitude: 11.977328,
      longitude: -14.80696,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Guyana",
    iso2: "GY",
    capital: "Georgetown",
    coordinates: {
      latitude: 4.630567,
      longitude: -59.0428783,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Haiti",
    iso2: "HT",
    capital: "Port-au-Prince",
    coordinates: {
      latitude: 18.874657,
      longitude: -72.165755,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Holy See",
    iso2: "VA",
    capital: "Vatican City",
    coordinates: {
      latitude: 41.903392,
      longitude: 12.453007,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Honduras",
    iso2: "HN",
    capital: "Tegucigalpa",
    coordinates: {
      latitude: 14.665456,
      longitude: -86.507575,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Hungary",
    iso2: "HU",
    capital: "Budapest",
    coordinates: {
      latitude: 47.205532,
      longitude: 19.326777,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Iceland",
    iso2: "IS",
    capital: "Reykjavik",
    coordinates: {
      latitude: 64.808213,
      longitude: -18.432283,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "India",
    iso2: "IN",
    capital: "New Delhi",
    coordinates: {
      latitude: 23.585461,
      longitude: 79.485195,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Indonesia",
    iso2: "ID",
    capital: "Jakarta",
    coordinates: {
      latitude: -0.865804,
      longitude: 114.419068,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Iran",
    iso2: "IR",
    capital: "Tehran",
    coordinates: {
      latitude: 31.662582,
      longitude: 54.405241,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Iraq",
    iso2: "IQ",
    capital: "Baghdad",
    coordinates: {
      latitude: 32.666975,
      longitude: 42.847625,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Ireland",
    iso2: "IE",
    capital: "Dublin",
    coordinates: {
      latitude: 53.0912,
      longitude: -7.933953,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Israel",
    iso2: "IL",
    capital: "Jerusalem",
    coordinates: {
      latitude: 32.044586,
      longitude: 34.882561,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Italy",
    iso2: "IT",
    capital: "Rome",
    coordinates: {
      latitude: 42.154783,
      longitude: 13.601936,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Jamaica",
    iso2: "JM",
    capital: "Kingston",
    coordinates: {
      latitude: 18.112992,
      longitude: -77.3011,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Japan",
    iso2: "JP",
    capital: "Tokyo",
    coordinates: {
      latitude: 35.872624,
      longitude: 138.231507,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Jordan",
    iso2: "JO",
    capital: "Amman",
    coordinates: {
      latitude: 31.15892,
      longitude: 36.624326,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Kazakhstan",
    iso2: "KZ",
    capital: "Nur-Sultan",
    coordinates: {
      latitude: 47.903065,
      longitude: 67.861791,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Kenya",
    iso2: "KE",
    capital: "Nairobi",
    coordinates: {
      latitude: 0.549435,
      longitude: 38.608963,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Kiribati",
    iso2: "KI",
    capital: "Tarawa",
    coordinates: {
      latitude: 1.85734,
      longitude: -157.38195,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Kuwait",
    iso2: "KW",
    capital: "Kuwait City",
    coordinates: {
      latitude: 29.26589,
      longitude: 47.518259,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Kyrgyzstan",
    iso2: "KG",
    capital: "Bishkek",
    coordinates: {
      latitude: 41.646544,
      longitude: 74.50135,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Laos",
    iso2: "LA",
    capital: "Vientiane",
    coordinates: {
      latitude: 19.840437,
      longitude: 102.343252,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Latvia",
    iso2: "LV",
    capital: "Riga",
    coordinates: {
      latitude: 56.725999,
      longitude: 25.19071,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Lebanon",
    iso2: "LB",
    capital: "Beirut",
    coordinates: {
      latitude: 33.942467,
      longitude: 35.869154,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Lesotho",
    iso2: "LS",
    capital: "Maseru",
    coordinates: {
      latitude: -29.645311,
      longitude: 28.254527,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Liberia",
    iso2: "LR",
    capital: "Monrovia",
    coordinates: {
      latitude: 6.207143,
      longitude: -9.25584,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Libya",
    iso2: "LY",
    capital: "Tripoli",
    coordinates: {
      latitude: 26.695617,
      longitude: 17.750764,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Liechtenstein",
    iso2: "LI",
    capital: "Vaduz",
    coordinates: {
      latitude: 47.144481,
      longitude: 9.55069,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Lithuania",
    iso2: "LT",
    capital: "Vilnius",
    coordinates: {
      latitude: 55.251663,
      longitude: 23.947517,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Luxembourg",
    iso2: "LU",
    capital: "Luxembourg City",
    coordinates: {
      latitude: 49.778279,
      longitude: 6.086537,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Madagascar",
    iso2: "MG",
    capital: "Antananarivo",
    coordinates: {
      latitude: -20.654105,
      longitude: 46.297423,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Malawi",
    iso2: "MW",
    capital: "Lilongwe",
    coordinates: {
      latitude: -13.384461,
      longitude: 34.136899,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Malaysia",
    iso2: "MY",
    capital: "Kuala Lumpur",
    coordinates: {
      latitude: 3.432499,
      longitude: 102.372359,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Maldives",
    iso2: "MV",
    capital: "Malé",
    coordinates: {
      latitude: -0.692959,
      longitude: 73.151248,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Mali",
    iso2: "ML",
    capital: "Bamako",
    coordinates: {
      latitude: 17.129281,
      longitude: -2.330446,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Malta",
    iso2: "MT",
    capital: "Valletta",
    coordinates: {
      latitude: 35.889992,
      longitude: 14.432581,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Marshall Islands",
    iso2: "MH",
    capital: "Majuro",
    coordinates: {
      latitude: 7.294033,
      longitude: 168.733056,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Mauritania",
    iso2: "MR",
    capital: "Nouakchott",
    coordinates: {
      latitude: 20.628589,
      longitude: -10.554376,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Mauritius",
    iso2: "MU",
    capital: "Port Louis",
    coordinates: {
      latitude: -20.309564,
      longitude: 57.559193,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Mexico",
    iso2: "MX",
    capital: "Mexico City",
    coordinates: {
      latitude: 23.353634,
      longitude: -102.497437,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Micronesia",
    iso2: "FM",
    capital: "Palikir",
    coordinates: {
      latitude: 6.872354,
      longitude: 158.22543,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Moldova",
    iso2: "MD",
    capital: "Chisinau",
    coordinates: {
      latitude: 47.337972,
      longitude: 28.574276,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Monaco",
    iso2: "MC",
    capital: "Monaco",
    coordinates: {
      latitude: 43.739932,
      longitude: 7.411903,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Mongolia",
    iso2: "MN",
    capital: "Ulaanbaatar",
    coordinates: {
      latitude: 46.497655,
      longitude: 103.731049,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Montenegro",
    iso2: "ME",
    capital: "Podgorica",
    coordinates: {
      latitude: 42.729189,
      longitude: 19.163936,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Morocco",
    iso2: "MA",
    capital: "Rabat",
    coordinates: {
      latitude: 31.597924,
      longitude: -6.419817,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Mozambique",
    iso2: "MZ",
    capital: "Maputo",
    coordinates: {
      latitude: -17.710513,
      longitude: 35.347942,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Myanmar",
    iso2: "MM",
    capital: "Naypyidaw",
    coordinates: {
      latitude: 20.681223,
      longitude: 96.299073,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Namibia",
    iso2: "NA",
    capital: "Windhoek",
    coordinates: {
      latitude: -22.514331,
      longitude: 17.203835,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Nauru",
    iso2: "NR",
    capital: "Yaren",
    coordinates: {
      latitude: -0.528838,
      longitude: 166.934209,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Nepal",
    iso2: "NP",
    capital: "Kathmandu",
    coordinates: {
      latitude: 28.033128,
      longitude: 83.895304,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Netherlands",
    iso2: "NL",
    capital: "Amsterdam",
    coordinates: {
      latitude: 52.089153,
      longitude: 5.453183,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "New Zealand",
    iso2: "NZ",
    capital: "Wellington",
    coordinates: {
      latitude: -42.090683,
      longitude: 173.257991,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Nicaragua",
    iso2: "NI",
    capital: "Managua",
    coordinates: {
      latitude: 12.609211,
      longitude: -84.824915,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Niger",
    iso2: "NE",
    capital: "Niamey",
    coordinates: {
      latitude: 17.022861,
      longitude: 8.893387,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Nigeria",
    iso2: "NG",
    capital: "Abuja",
    coordinates: {
      latitude: 9.25629,
      longitude: 7.972401,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "North Macedonia",
    iso2: "MK",
    capital: "Skopje",
    coordinates: {
      latitude: 41.515037,
      longitude: 21.683111,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "North Korea",
    iso2: "KP",
    capital: "Pyongyang",
    coordinates: {
      latitude: 39.917408,
      longitude: 126.981493,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Norway",
    iso2: "NO",
    capital: "Oslo",
    coordinates: {
      latitude: 62.384645,
      longitude: 9.852518,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Oman",
    iso2: "OM",
    capital: "Muscat",
    coordinates: {
      latitude: 20.357386,
      longitude: 56.944317,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Pakistan",
    iso2: "PK",
    capital: "Islamabad",
    coordinates: {
      latitude: 29.681723,
      longitude: 69.287414,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Palau",
    iso2: "PW",
    capital: "Ngerulmud",
    coordinates: {
      latitude: 7.478309,
      longitude: 134.562218,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Palestine",
    iso2: "PS",
    capital: "Ramallah",
    coordinates: {
      latitude: 31.742455,
      longitude: 35.281704,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Panama",
    iso2: "PA",
    capital: "Panama City",
    coordinates: {
      latitude: 8.432969,
      longitude: -80.810336,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Papua New Guinea",
    iso2: "PG",
    capital: "Port Moresby",
    coordinates: {
      latitude: -6.720311,
      longitude: 145.103981,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Paraguay",
    iso2: "PY",
    capital: "Asunción",
    coordinates: {
      latitude: -23.519314,
      longitude: -58.249823,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Peru",
    iso2: "PE",
    capital: "Lima",
    coordinates: {
      latitude: -9.693226,
      longitude: -75.099652,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Philippines",
    iso2: "PH",
    capital: "Manila",
    coordinates: {
      latitude: 14.275166,
      longitude: 121.0534,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Poland",
    iso2: "PL",
    capital: "Warsaw",
    coordinates: {
      latitude: 52.227564,
      longitude: 19.063668,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Portugal",
    iso2: "PT",
    capital: "Lisbon",
    coordinates: {
      latitude: 39.537919,
      longitude: -8.146208,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Qatar",
    iso2: "QA",
    capital: "Doha",
    coordinates: {
      latitude: 25.260696,
      longitude: 51.207467,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Romania",
    iso2: "RO",
    capital: "Bucharest",
    coordinates: {
      latitude: 45.674046,
      longitude: 24.797751,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Russia",
    iso2: "RU",
    capital: "Moscow",
    coordinates: {
      latitude: 61.40741,
      longitude: 92.863749,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Rwanda",
    iso2: "RW",
    capital: "Kigali",
    coordinates: {
      latitude: -2.061558,
      longitude: 29.918611,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "KN",
    capital: "Basseterre",
    coordinates: {
      latitude: 17.315752,
      longitude: -62.732322,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Saint Lucia",
    iso2: "LC",
    capital: "Castries",
    coordinates: {
      latitude: 13.878137,
      longitude: -60.978471,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "VC",
    capital: "Kingstown",
    coordinates: {
      latitude: 13.228186,
      longitude: -61.192829,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Samoa",
    iso2: "WS",
    capital: "Apia",
    coordinates: {
      latitude: -13.659545,
      longitude: -172.411991,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "San Marino",
    iso2: "SM",
    capital: "San Marino",
    coordinates: {
      latitude: 43.926553,
      longitude: 12.448472,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Sao Tome and Principe",
    iso2: "ST",
    capital: "São Tomé",
    coordinates: {
      latitude: 0.21847,
      longitude: 6.599868,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Saudi Arabia",
    iso2: "SA",
    capital: "Riyadh",
    coordinates: {
      latitude: 22.924822,
      longitude: 45.067205,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Senegal",
    iso2: "SN",
    capital: "Dakar",
    coordinates: {
      latitude: 14.208736,
      longitude: -14.631658,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Serbia",
    iso2: "RS",
    capital: "Belgrade",
    coordinates: {
      latitude: 43.983086,
      longitude: 20.797826,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Seychelles",
    iso2: "SC",
    capital: "Victoria",
    coordinates: {
      latitude: -4.674943,
      longitude: 55.476781,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Sierra Leone",
    iso2: "SL",
    capital: "Freetown",
    coordinates: {
      latitude: 8.392917,
      longitude: -11.915556,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Singapore",
    iso2: "SG",
    capital: "Singapore",
    coordinates: {
      latitude: 1.321546,
      longitude: 103.83256,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Slovakia",
    iso2: "SK",
    capital: "Bratislava",
    coordinates: {
      latitude: 48.808074,
      longitude: 19.265246,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Slovenia",
    iso2: "SI",
    capital: "Ljubljana",
    coordinates: {
      latitude: 46.069129,
      longitude: 14.749149,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Solomon Islands",
    iso2: "SB",
    capital: "Honiara",
    coordinates: {
      latitude: -9.662966,
      longitude: 160.272396,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Somalia",
    iso2: "SO",
    capital: "Mogadishu",
    coordinates: {
      latitude: 3.132266,
      longitude: 45.003051,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "South Africa",
    iso2: "ZA",
    capital: "Pretoria",
    coordinates: {
      latitude: -30.644667,
      longitude: 26.1406985,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "South Korea",
    iso2: "KR",
    capital: "Seoul",
    coordinates: {
      latitude: 36.405851,
      longitude: 128.015221,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "South Sudan",
    iso2: "SS",
    capital: "Juba",
    coordinates: {
      latitude: 6.91434,
      longitude: 30.242143,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Spain",
    iso2: "ES",
    capital: "Madrid",
    coordinates: {
      latitude: 40.068751,
      longitude: -3.403233,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Sri Lanka",
    iso2: "LK",
    capital: "Colombo",
    coordinates: {
      latitude: 7.305781,
      longitude: 80.633505,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Sudan",
    iso2: "SD",
    capital: "Khartoum",
    coordinates: {
      latitude: 15.465887,
      longitude: 30.061608,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Suriname",
    iso2: "SR",
    capital: "Paramaribo",
    coordinates: {
      latitude: 3.901328,
      longitude: -55.683175,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Sweden",
    iso2: "SE",
    capital: "Stockholm",
    coordinates: {
      latitude: 62.515089,
      longitude: 15.7967,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Switzerland",
    iso2: "CH",
    capital: "Bern",
    coordinates: {
      latitude: 46.678978,
      longitude: 8.11841,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Syria",
    iso2: "SY",
    capital: "Damascus",
    coordinates: {
      latitude: 34.804443,
      longitude: 38.62534,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Tajikistan",
    iso2: "TJ",
    capital: "Dushanbe",
    coordinates: {
      latitude: 38.840397,
      longitude: 70.953607,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Tanzania",
    iso2: "TZ",
    capital: "Dodoma",
    coordinates: {
      latitude: -6.760545,
      longitude: 34.724184,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Thailand",
    iso2: "TH",
    capital: "Bangkok",
    coordinates: {
      latitude: 14.88317,
      longitude: 101.137365,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Timor-Leste",
    iso2: "TL",
    capital: "Dili",
    coordinates: {
      latitude: -8.846764,
      longitude: 125.898198,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Togo",
    iso2: "TG",
    capital: "Lome",
    coordinates: {
      latitude: 8.416691,
      longitude: 1.091019,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Tonga",
    iso2: "TO",
    capital: "Nuku'alofa",
    coordinates: {
      latitude: -21.227083,
      longitude: -175.15126,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Trinidad and Tobago",
    iso2: "TT",
    capital: "Port of Spain",
    coordinates: {
      latitude: 10.33685,
      longitude: -61.253173,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Tunisia",
    iso2: "TN",
    capital: "Tunis",
    coordinates: {
      latitude: 33.616905,
      longitude: 9.523697,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Turkey",
    iso2: "TR",
    capital: "Ankara",
    coordinates: {
      latitude: 39.309076,
      longitude: 35.248818,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "Turkmenistan",
    iso2: "TM",
    capital: "Ashgabat",
    coordinates: {
      latitude: 39.287759,
      longitude: 59.25801,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Tuvalu",
    iso2: "TV",
    capital: "Funafuti",
    coordinates: {
      latitude: -8.526209,
      longitude: 179.193391,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Uganda",
    iso2: "UG",
    capital: "Kampala",
    coordinates: {
      latitude: 1.311794,
      longitude: 32.462875,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Ukraine",
    iso2: "UA",
    capital: "Kyiv",
    coordinates: {
      latitude: 49.215157,
      longitude: 31.63328,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "United Arab Emirates",
    iso2: "AE",
    capital: "Abu Dhabi",
    coordinates: {
      latitude: 24.011516,
      longitude: 54.780112,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "United Kingdom",
    iso2: "GB",
    capital: "London",
    coordinates: {
      latitude: 52.8876,
      longitude: -1.557282,
    },
    continent: "Europe",
    isPopular: false,
  },
  {
    name: "United States",
    iso2: "US",
    capital: "Washington, D.C.",
    coordinates: {
      latitude: 40.182226,
      longitude: -99.834143,
    },
    continent: "North America",
    isPopular: false,
  },
  {
    name: "Uruguay",
    iso2: "UY",
    capital: "Montevideo",
    coordinates: {
      latitude: -33.012919,
      longitude: -55.999118,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Uzbekistan",
    iso2: "UZ",
    capital: "Tashkent",
    coordinates: {
      latitude: 41.606114,
      longitude: 63.784536,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Vanuatu",
    iso2: "VU",
    capital: "Port Vila",
    coordinates: {
      latitude: -15.461028,
      longitude: 167.04519,
    },
    continent: "Oceania",
    isPopular: false,
  },
  {
    name: "Venezuela",
    iso2: "VE",
    capital: "Caracas",
    coordinates: {
      latitude: 6.825358,
      longitude: -64.925016,
    },
    continent: "South America",
    isPopular: false,
  },
  {
    name: "Vietnam",
    iso2: "VN",
    capital: "Hanoi",
    coordinates: {
      latitude: 15.793322,
      longitude: 108.107031,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Yemen",
    iso2: "YE",
    capital: "Sanaa",
    coordinates: {
      latitude: 15.568928,
      longitude: 47.957065,
    },
    continent: "Asia",
    isPopular: false,
  },
  {
    name: "Zambia",
    iso2: "ZM",
    capital: "Lusaka",
    coordinates: {
      latitude: -13.791394,
      longitude: 27.8535,
    },
    continent: "Africa",
    isPopular: false,
  },
  {
    name: "Zimbabwe",
    iso2: "ZW",
    capital: "Harare",
    coordinates: {
      latitude: -19.173357,
      longitude: 29.862368,
    },
    continent: "Africa",
    isPopular: false,
  },
];
