export const CountriesList = [
  {
    name: "Afghanistan",
    iso2: "AF",
    capital: "Kabul",
    phone: "+93",
    emergencyNumber: "112",
  },
  {
    name: "Albania",
    iso2: "AL",
    capital: "Tirana",
    phone: "+355",
    emergencyNumber: "112",
  },
  {
    name: "Algeria",
    iso2: "DZ",
    capital: "Algiers",
    phone: "+213",
    emergencyNumber: "17",
  },
  {
    name: "Andorra",
    iso2: "AD",
    capital: "Andorra la Vella",
    phone: "+376",
    emergencyNumber: "112",
  },
  {
    name: "Angola",
    iso2: "AO",
    capital: "Luanda",
    phone: "+244",
    emergencyNumber: "112",
  },
  {
    name: "Antigua and Barbuda",
    iso2: "AG",
    capital: "St. John's",
    phone: "+1 268",
    emergencyNumber: "911",
  },
  {
    name: "Argentina",
    iso2: "AR",
    capital: "Buenos Aires",
    phone: "+54",
    emergencyNumber: "911",
  },
  {
    name: "Armenia",
    iso2: "AM",
    capital: "Yerevan",
    phone: "+374",
    emergencyNumber: "112",
  },
  {
    name: "Australia",
    iso2: "AU",
    capital: "Canberra",
    phone: "+61",
    emergencyNumber: "000",
  },
  {
    name: "Austria",
    iso2: "AT",
    capital: "Vienna",
    phone: "+43",
    emergencyNumber: "112",
  },
  {
    name: "Azerbaijan",
    iso2: "AZ",
    capital: "Baku",
    phone: "+994",
    emergencyNumber: "112",
  },
  {
    name: "Bahamas",
    iso2: "BS",
    capital: "Nassau",
    phone: "+1 242",
    emergencyNumber: "919",
  },
  {
    name: "Bahrain",
    iso2: "BH",
    capital: "Manama",
    phone: "+973",
    emergencyNumber: "999",
  },
  {
    name: "Bangladesh",
    iso2: "BD",
    capital: "Dhaka",
    phone: "+880",
    emergencyNumber: "999",
  },
  {
    name: "Barbados",
    iso2: "BB",
    capital: "Bridgetown",
    phone: "+1 246",
    emergencyNumber: "911",
  },
  {
    name: "Belarus",
    iso2: "BY",
    capital: "Minsk",
    phone: "+375",
    emergencyNumber: "112",
  },
  {
    name: "Belgium",
    iso2: "BE",
    capital: "Brussels",
    phone: "+32",
    emergencyNumber: "112",
  },
  {
    name: "Belize",
    iso2: "BZ",
    capital: "Belmopan",
    phone: "+501",
    emergencyNumber: "911",
  },
  {
    name: "Benin",
    iso2: "BJ",
    capital: "Porto-Novo",
    phone: "+229",
    emergencyNumber: "117",
  },
  {
    name: "Bhutan",
    iso2: "BT",
    capital: "Thimphu",
    phone: "+975",
    emergencyNumber: "112",
  },
  {
    name: "Bolivia",
    iso2: "BO",
    capital: "La Paz",
    phone: "+591",
    emergencyNumber: "110",
  },
  {
    name: "Bosnia and Herzegovina",
    iso2: "BA",
    capital: "Sarajevo",
    phone: "+387",
    emergencyNumber: "112",
  },
  {
    name: "Botswana",
    iso2: "BW",
    capital: "Gaborone",
    phone: "+267",
    emergencyNumber: "999",
  },
  {
    name: "Brazil",
    iso2: "BR",
    capital: "Brasília",
    phone: "+55",
    emergencyNumber: "190",
  },
  {
    name: "Brunei",
    iso2: "BN",
    capital: "Bandar Seri Begawan",
    phone: "+673",
    emergencyNumber: "995",
  },
  {
    name: "Bulgaria",
    iso2: "BG",
    capital: "Sofia",
    phone: "+359",
    emergencyNumber: "112",
  },
  {
    name: "Burkina Faso",
    iso2: "BF",
    capital: "Ouagadougou",
    phone: "+226",
    emergencyNumber: "17",
  },
  {
    name: "Burundi",
    iso2: "BI",
    capital: "Bujumbura",
    phone: "+257",
    emergencyNumber: "112",
  },
  {
    name: "Côte d'Ivoire",
    iso2: "CI",
    capital: "Yamoussoukro",
    phone: "+225",
    emergencyNumber: "185",
  },
  {
    name: "Cabo Verde",
    iso2: "CV",
    capital: "Praia",
    phone: "+238",
    emergencyNumber: "130",
  },
  {
    name: "Cambodia",
    iso2: "KH",
    capital: "Phnom Penh",
    phone: "+855",
    emergencyNumber: "117",
  },
  {
    name: "Cameroon",
    iso2: "CM",
    capital: "Yaoundé",
    phone: "+237",
    emergencyNumber: "112",
  },
  {
    name: "Canada",
    iso2: "CA",
    capital: "Ottawa",
    phone: "+1",
    emergencyNumber: "911",
  },
  {
    name: "Central African Republic",
    iso2: "CF",
    capital: "Bangui",
    phone: "+236",
    emergencyNumber: "117",
  },
  {
    name: "Chad",
    iso2: "TD",
    capital: "N'Djamena",
    phone: "+235",
    emergencyNumber: "17",
  },
  {
    name: "Chile",
    iso2: "CL",
    capital: "Santiago",
    phone: "+56",
    emergencyNumber: "131",
  },
  {
    name: "China",
    iso2: "CN",
    capital: "Beijing",
    phone: "+86",
    emergencyNumber: "110",
  },
  {
    name: "Colombia",
    iso2: "CO",
    capital: "Bogotá",
    phone: "+57",
    emergencyNumber: "123",
  },
  {
    name: "Comoros",
    iso2: "KM",
    capital: "Moroni",
    phone: "+269",
    emergencyNumber: "17",
  },
  {
    name: "Congo (Congo-Brazzaville)",
    iso2: "CG",
    capital: "Brazzaville",
    phone: "+242",
    emergencyNumber: "117",
  },
  {
    name: "Costa Rica",
    iso2: "CR",
    capital: "San José",
    phone: "+506",
    emergencyNumber: "911",
  },
  {
    name: "Croatia",
    iso2: "HR",
    capital: "Zagreb",
    phone: "+385",
    emergencyNumber: "112",
  },
  {
    name: "Cuba",
    iso2: "CU",
    capital: "Havana",
    phone: "+53",
    emergencyNumber: "106",
  },
  {
    name: "Cyprus",
    iso2: "CY",
    capital: "Nicosia",
    phone: "+357",
    emergencyNumber: "112",
  },
  {
    name: "Czechia (Czech Republic)",
    iso2: "CZ",
    capital: "Prague",
    phone: "+420",
    emergencyNumber: "112",
  },
  {
    name: "Democratic Republic of the Congo (Congo-Kinshasa)",
    iso2: "CD",
    capital: "Kinshasa",
    phone: "+243",
    emergencyNumber: "112",
  },
  {
    name: "Denmark",
    iso2: "DK",
    capital: "Copenhagen",
    phone: "+45",
    emergencyNumber: "112",
  },
  {
    name: "Djibouti",
    iso2: "DJ",
    capital: "Djibouti",
    phone: "+253",
    emergencyNumber: "17",
  },
  {
    name: "Dominica",
    iso2: "DM",
    capital: "Roseau",
    phone: "+1 767",
    emergencyNumber: "999",
  },
  {
    name: "Dominican Republic",
    iso2: "DO",
    capital: "Santo Domingo",
    phone: "+1 809",
    emergencyNumber: "911",
  },
  {
    name: "Ecuador",
    iso2: "EC",
    capital: "Quito",
    phone: "+593",
    emergencyNumber: "911",
  },
  {
    name: "Egypt",
    iso2: "EG",
    capital: "Cairo",
    phone: "+20",
    emergencyNumber: "122",
  },
  {
    name: "El Salvador",
    iso2: "SV",
    capital: "San Salvador",
    phone: "+503",
    emergencyNumber: "911",
  },
  {
    name: "Equatorial Guinea",
    iso2: "GQ",
    capital: "Malabo",
    phone: "+240",
    emergencyNumber: "112",
  },
  {
    name: "Eritrea",
    iso2: "ER",
    capital: "Asmara",
    phone: "+291",
    emergencyNumber: "116",
  },
  {
    name: "Estonia",
    iso2: "EE",
    capital: "Tallinn",
    phone: "+372",
    emergencyNumber: "112",
  },
  {
    name: "Eswatini (Swaziland)",
    iso2: "SZ",
    capital: "Mbabane",
    phone: "+268",
    emergencyNumber: "999",
  },
  {
    name: "Ethiopia",
    iso2: "ET",
    capital: "Addis Ababa",
    phone: "+251",
    emergencyNumber: "911",
  },
  {
    name: "Fiji",
    iso2: "FJ",
    capital: "Suva",
    phone: "+679",
    emergencyNumber: "911",
  },
  {
    name: "Finland",
    iso2: "FI",
    capital: "Helsinki",
    phone: "+358",
    emergencyNumber: "112",
  },
  {
    name: "France",
    iso2: "FR",
    capital: "Paris",
    phone: "+33",
    emergencyNumber: "112",
  },
  {
    name: "Gabon",
    iso2: "GA",
    capital: "Libreville",
    phone: "+241",
    emergencyNumber: "1300",
  },
  {
    name: "Gambia",
    iso2: "GM",
    capital: "Banjul",
    phone: "+220",
    emergencyNumber: "117",
  },
  {
    name: "Georgia",
    iso2: "GE",
    capital: "Tbilisi",
    phone: "+995",
    emergencyNumber: "112",
  },
  {
    name: "Germany",
    iso2: "DE",
    capital: "Berlin",
    phone: "+49",
    emergencyNumber: "112",
  },
  {
    name: "Ghana",
    iso2: "GH",
    capital: "Accra",
    phone: "+233",
    emergencyNumber: "112",
  },
  {
    name: "Greece",
    iso2: "GR",
    capital: "Athens",
    phone: "+30",
    emergencyNumber: "112",
  },
  {
    name: "Grenada",
    iso2: "GD",
    capital: "St. George's",
    phone: "+1 473",
    emergencyNumber: "911",
  },
  {
    name: "Guatemala",
    iso2: "GT",
    capital: "Guatemala City",
    phone: "+502",
    emergencyNumber: "123",
  },
  {
    name: "Guinea",
    iso2: "GN",
    capital: "Conakry",
    phone: "+224",
    emergencyNumber: "122",
  },
  {
    name: "Guinea-Bissau",
    iso2: "GW",
    capital: "Bissau",
    phone: "+245",
    emergencyNumber: "117",
  },
  {
    name: "Guyana",
    iso2: "GY",
    capital: "Georgetown",
    phone: "+592",
    emergencyNumber: "911",
  },
  {
    name: "Haiti",
    iso2: "HT",
    capital: "Port-au-Prince",
    phone: "+509",
    emergencyNumber: "114",
  },
  {
    name: "Holy See",
    iso2: "VA",
    capital: "Vatican City",
    phone: "+379",
    emergencyNumber: "112",
  },
  {
    name: "Honduras",
    iso2: "HN",
    capital: "Tegucigalpa",
    phone: "+504",
    emergencyNumber: "199",
  },
  {
    name: "Hungary",
    iso2: "HU",
    capital: "Budapest",
    phone: "+36",
    emergencyNumber: "112",
  },
  {
    name: "Iceland",
    iso2: "IS",
    capital: "Reykjavik",
    phone: "+354",
    emergencyNumber: "112",
  },
  {
    name: "India",
    iso2: "IN",
    capital: "New Delhi",
    phone: "+91",
    emergencyNumber: "112",
  },
  {
    name: "Indonesia",
    iso2: "ID",
    capital: "Jakarta",
    phone: "+62",
    emergencyNumber: "112",
  },
  {
    name: "Iran",
    iso2: "IR",
    capital: "Tehran",
    phone: "+98",
    emergencyNumber: "110",
  },
  {
    name: "Iraq",
    iso2: "IQ",
    capital: "Baghdad",
    phone: "+964",
    emergencyNumber: "112",
  },
  {
    name: "Ireland",
    iso2: "IE",
    capital: "Dublin",
    phone: "+353",
    emergencyNumber: "112",
  },
  {
    name: "Israel",
    iso2: "IL",
    capital: "Jerusalem",
    phone: "+972",
    emergencyNumber: "100",
  },
  {
    name: "Italy",
    iso2: "IT",
    capital: "Rome",
    phone: "+39",
    emergencyNumber: "112",
  },
  {
    name: "Jamaica",
    iso2: "JM",
    capital: "Kingston",
    phone: "+1 876",
    emergencyNumber: "119",
  },
  {
    name: "Japan",
    iso2: "JP",
    capital: "Tokyo",
    phone: "+81",
    emergencyNumber: "110",
  },
  {
    name: "Jordan",
    iso2: "JO",
    capital: "Amman",
    phone: "+962",
    emergencyNumber: "112",
  },
  {
    name: "Kazakhstan",
    iso2: "KZ",
    capital: "Nur-Sultan",
    phone: "+7",
    emergencyNumber: "112",
  },
  {
    name: "Kenya",
    iso2: "KE",
    capital: "Nairobi",
    phone: "+254",
    emergencyNumber: "999",
  },
  {
    name: "Kiribati",
    iso2: "KI",
    capital: "Tarawa",
    phone: "+686",
    emergencyNumber: "999",
  },
  {
    name: "Kuwait",
    iso2: "KW",
    capital: "Kuwait City",
    phone: "+965",
    emergencyNumber: "112",
  },
  {
    name: "Kyrgyzstan",
    iso2: "KG",
    capital: "Bishkek",
    phone: "+996",
    emergencyNumber: "102",
  },
  {
    name: "Laos",
    iso2: "LA",
    capital: "Vientiane",
    phone: "+856",
    emergencyNumber: "119",
  },
  {
    name: "Latvia",
    iso2: "LV",
    capital: "Riga",
    phone: "+371",
    emergencyNumber: "112",
  },
  {
    name: "Lebanon",
    iso2: "LB",
    capital: "Beirut",
    phone: "+961",
    emergencyNumber: "112",
  },
  {
    name: "Lesotho",
    iso2: "LS",
    capital: "Maseru",
    phone: "+266",
    emergencyNumber: "123",
  },
  {
    name: "Liberia",
    iso2: "LR",
    capital: "Monrovia",
    phone: "+231",
    emergencyNumber: "911",
  },
  {
    name: "Libya",
    iso2: "LY",
    capital: "Tripoli",
    phone: "+218",
    emergencyNumber: "1515",
  },
  {
    name: "Liechtenstein",
    iso2: "LI",
    capital: "Vaduz",
    phone: "+423",
    emergencyNumber: "112",
  },
  {
    name: "Lithuania",
    iso2: "LT",
    capital: "Vilnius",
    phone: "+370",
    emergencyNumber: "112",
  },
  {
    name: "Luxembourg",
    iso2: "LU",
    capital: "Luxembourg City",
    phone: "+352",
    emergencyNumber: "112",
  },
  {
    name: "Madagascar",
    iso2: "MG",
    capital: "Antananarivo",
    phone: "+261",
    emergencyNumber: "117",
  },
  {
    name: "Malawi",
    iso2: "MW",
    capital: "Lilongwe",
    phone: "+265",
    emergencyNumber: "997",
  },
  {
    name: "Malaysia",
    iso2: "MY",
    capital: "Kuala Lumpur",
    phone: "+60",
    emergencyNumber: "999",
  },
  {
    name: "Maldives",
    iso2: "MV",
    capital: "Malé",
    phone: "+960",
    emergencyNumber: "119",
  },
  {
    name: "Mali",
    iso2: "ML",
    capital: "Bamako",
    phone: "+223",
    emergencyNumber: "17",
  },
  {
    name: "Malta",
    iso2: "MT",
    capital: "Valletta",
    phone: "+356",
    emergencyNumber: "112",
  },
  {
    name: "Marshall Islands",
    iso2: "MH",
    capital: "Majuro",
    phone: "+692",
    emergencyNumber: "911",
  },
  {
    name: "Mauritania",
    iso2: "MR",
    capital: "Nouakchott",
    phone: "+222",
    emergencyNumber: "117",
  },
  {
    name: "Mauritius",
    iso2: "MU",
    capital: "Port Louis",
    phone: "+230",
    emergencyNumber: "114",
  },
  {
    name: "Mexico",
    iso2: "MX",
    capital: "Mexico City",
    phone: "+52",
    emergencyNumber: "911",
  },
  {
    name: "Micronesia",
    iso2: "FM",
    capital: "Palikir",
    phone: "+691",
    emergencyNumber: "911",
  },
  {
    name: "Moldova",
    iso2: "MD",
    capital: "Chisinau",
    phone: "+373",
    emergencyNumber: "112",
  },
  {
    name: "Monaco",
    iso2: "MC",
    capital: "Monaco",
    phone: "+377",
    emergencyNumber: "112",
  },
  {
    name: "Mongolia",
    iso2: "MN",
    capital: "Ulaanbaatar",
    phone: "+976",
    emergencyNumber: "102",
  },
  {
    name: "Montenegro",
    iso2: "ME",
    capital: "Podgorica",
    phone: "+382",
    emergencyNumber: "112",
  },
  {
    name: "Morocco",
    iso2: "MA",
    capital: "Rabat",
    phone: "+212",
    emergencyNumber: "19",
  },
  {
    name: "Mozambique",
    iso2: "MZ",
    capital: "Maputo",
    phone: "+258",
    emergencyNumber: "117",
  },
  {
    name: "Myanmar (Burma)",
    iso2: "MM",
    capital: "Naypyidaw",
    phone: "+95",
    emergencyNumber: "199",
  },
  {
    name: "Namibia",
    iso2: "NA",
    capital: "Windhoek",
    phone: "+264",
    emergencyNumber: "112",
  },
  {
    name: "Nauru",
    iso2: "NR",
    capital: "Yaren",
    phone: "+674",
    emergencyNumber: "110",
  },
  {
    name: "Nepal",
    iso2: "NP",
    capital: "Kathmandu",
    phone: "+977",
    emergencyNumber: "100",
  },
  {
    name: "Netherlands",
    iso2: "NL",
    capital: "Amsterdam",
    phone: "+31",
    emergencyNumber: "112",
  },
  {
    name: "New Zealand",
    iso2: "NZ",
    capital: "Wellington",
    phone: "+64",
    emergencyNumber: "111",
  },
  {
    name: "Nicaragua",
    iso2: "NI",
    capital: "Managua",
    phone: "+505",
    emergencyNumber: "118",
  },
  {
    name: "Niger",
    iso2: "NE",
    capital: "Niamey",
    phone: "+227",
    emergencyNumber: "17",
  },
  {
    name: "Nigeria",
    iso2: "NG",
    capital: "Abuja",
    phone: "+234",
    emergencyNumber: "112",
  },
  {
    name: "North Macedonia",
    iso2: "MK",
    capital: "Skopje",
    phone: "+389",
    emergencyNumber: "192",
  },
  {
    name: "Norway",
    iso2: "NO",
    capital: "Oslo",
    phone: "+47",
    emergencyNumber: "112",
  },
  {
    name: "Oman",
    iso2: "OM",
    capital: "Muscat",
    phone: "+968",
    emergencyNumber: "9999",
  },
  {
    name: "Pakistan",
    iso2: "PK",
    capital: "Islamabad",
    phone: "+92",
    emergencyNumber: "15",
  },
  {
    name: "Palau",
    iso2: "PW",
    capital: "Ngerulmud",
    phone: "+680",
    emergencyNumber: "911",
  },
  {
    name: "Palestine State",
    iso2: "PS",
    capital: "Ramallah",
    phone: "+970",
    emergencyNumber: "101",
  },
  {
    name: "Panama",
    iso2: "PA",
    capital: "Panama City",
    phone: "+507",
    emergencyNumber: "911",
  },
  {
    name: "Papua New Guinea",
    iso2: "PG",
    capital: "Port Moresby",
    phone: "+675",
    emergencyNumber: "000",
  },
  {
    name: "Paraguay",
    iso2: "PY",
    capital: "Asunción",
    phone: "+595",
    emergencyNumber: "911",
  },
  {
    name: "Peru",
    iso2: "PE",
    capital: "Lima",
    phone: "+51",
    emergencyNumber: "105",
  },
  {
    name: "Philippines",
    iso2: "PH",
    capital: "Manila",
    phone: "+63",
    emergencyNumber: "911",
  },
  {
    name: "Poland",
    iso2: "PL",
    capital: "Warsaw",
    phone: "+48",
    emergencyNumber: "112",
  },
  {
    name: "Portugal",
    iso2: "PT",
    capital: "Lisbon",
    phone: "+351",
    emergencyNumber: "112",
  },
  {
    name: "Qatar",
    iso2: "QA",
    capital: "Doha",
    phone: "+974",
    emergencyNumber: "999",
  },
  {
    name: "Romania",
    iso2: "RO",
    capital: "Bucharest",
    phone: "+40",
    emergencyNumber: "112",
  },
  {
    name: "Russia",
    iso2: "RU",
    capital: "Moscow",
    phone: "+7",
    emergencyNumber: "112",
  },
  {
    name: "Rwanda",
    iso2: "RW",
    capital: "Kigali",
    phone: "+250",
    emergencyNumber: "112",
  },
  {
    name: "Saint Kitts and Nevis",
    iso2: "KN",
    capital: "Basseterre",
    phone: "+1 869",
    emergencyNumber: "911",
  },
  {
    name: "Saint Lucia",
    iso2: "LC",
    capital: "Castries",
    phone: "+1 758",
    emergencyNumber: "911",
  },
  {
    name: "Saint Vincent and the Grenadines",
    iso2: "VC",
    capital: "Kingstown",
    phone: "+1 784",
    emergencyNumber: "911",
  },
  {
    name: "Samoa",
    iso2: "WS",
    capital: "Apia",
    phone: "+685",
    emergencyNumber: "995",
  },
  {
    name: "San Marino",
    iso2: "SM",
    capital: "San Marino",
    phone: "+378",
    emergencyNumber: "112",
  },
  {
    name: "Sao Tome and Principe",
    iso2: "ST",
    capital: "São Tomé",
    phone: "+239",
    emergencyNumber: "112",
  },
  {
    name: "Saudi Arabia",
    iso2: "SA",
    capital: "Riyadh",
    phone: "+966",
    emergencyNumber: "911",
  },
  {
    name: "Senegal",
    iso2: "SN",
    capital: "Dakar",
    phone: "+221",
    emergencyNumber: "17",
  },
  {
    name: "Serbia",
    iso2: "RS",
    capital: "Belgrade",
    phone: "+381",
    emergencyNumber: "192",
  },
  {
    name: "Seychelles",
    iso2: "SC",
    capital: "Victoria",
    phone: "+248",
    emergencyNumber: "999",
  },
  {
    name: "Sierra Leone",
    iso2: "SL",
    capital: "Freetown",
    phone: "+232",
    emergencyNumber: "999",
  },
  {
    name: "Singapore",
    iso2: "SG",
    capital: "Singapore",
    phone: "+65",
    emergencyNumber: "995",
  },
  {
    name: "Slovakia",
    iso2: "SK",
    capital: "Bratislava",
    phone: "+421",
    emergencyNumber: "112",
  },
  {
    name: "Slovenia",
    iso2: "SI",
    capital: "Ljubljana",
    phone: "+386",
    emergencyNumber: "112",
  },
  {
    name: "Solomon Islands",
    iso2: "SB",
    capital: "Honiara",
    phone: "+677",
    emergencyNumber: "999",
  },
  {
    name: "Somalia",
    iso2: "SO",
    capital: "Mogadishu",
    phone: "+252",
    emergencyNumber: "888",
  },
  {
    name: "South Africa",
    iso2: "ZA",
    capital: "Pretoria",
    phone: "+27",
    emergencyNumber: "10111",
  },
  {
    name: "South Korea",
    iso2: "KR",
    capital: "Seoul",
    phone: "+82",
    emergencyNumber: "112",
  },
  {
    name: "South Sudan",
    iso2: "SS",
    capital: "Juba",
    phone: "+211",
    emergencyNumber: "977",
  },
  {
    name: "Spain",
    iso2: "ES",
    capital: "Madrid",
    phone: "+34",
    emergencyNumber: "112",
  },
  {
    name: "Sri Lanka",
    iso2: "LK",
    capital: "Colombo",
    phone: "+94",
    emergencyNumber: "119",
  },
  {
    name: "Sudan",
    iso2: "SD",
    capital: "Khartoum",
    phone: "+249",
    emergencyNumber: "999",
  },
  {
    name: "Suriname",
    iso2: "SR",
    capital: "Paramaribo",
    phone: "+597",
    emergencyNumber: "115",
  },
  {
    name: "Sweden",
    iso2: "SE",
    capital: "Stockholm",
    phone: "+46",
    emergencyNumber: "112",
  },
  {
    name: "Switzerland",
    iso2: "CH",
    capital: "Bern",
    phone: "+41",
    emergencyNumber: "112",
  },
  {
    name: "Syria",
    iso2: "SY",
    capital: "Damascus",
    phone: "+963",
    emergencyNumber: "112",
  },
  {
    name: "Tajikistan",
    iso2: "TJ",
    capital: "Dushanbe",
    phone: "+992",
    emergencyNumber: "112",
  },
  {
    name: "Tanzania",
    iso2: "TZ",
    capital: "Dodoma",
    phone: "+255",
    emergencyNumber: "112",
  },
  {
    name: "Thailand",
    iso2: "TH",
    capital: "Bangkok",
    phone: "+66",
    emergencyNumber: "191",
  },
  {
    name: "Timor-Leste",
    iso2: "TL",
    capital: "Dili",
    phone: "+670",
    emergencyNumber: "112",
  },
  {
    name: "Togo",
    iso2: "TG",
    capital: "Lome",
    phone: "+228",
    emergencyNumber: "117",
  },
  {
    name: "Tonga",
    iso2: "TO",
    capital: "Nuku'alofa",
    phone: "+676",
    emergencyNumber: "911",
  },
  {
    name: "Trinidad and Tobago",
    iso2: "TT",
    capital: "Port of Spain",
    phone: "+1 868",
    emergencyNumber: "999",
  },
  {
    name: "Tunisia",
    iso2: "TN",
    capital: "Tunis",
    phone: "+216",
    emergencyNumber: "190",
  },
  {
    name: "Turkey",
    iso2: "TR",
    capital: "Ankara",
    phone: "+90",
    emergencyNumber: "112",
  },
  {
    name: "Turkmenistan",
    iso2: "TM",
    capital: "Ashgabat",
    phone: "+993",
    emergencyNumber: "101",
  },
  {
    name: "Tuvalu",
    iso2: "TV",
    capital: "Funafuti",
    phone: "+688",
    emergencyNumber: "911",
  },
  {
    name: "Uganda",
    iso2: "UG",
    capital: "Kampala",
    phone: "+256",
    emergencyNumber: "999",
  },
  {
    name: "Ukraine",
    iso2: "UA",
    capital: "Kyiv",
    phone: "+380",
    emergencyNumber: "112",
  },
  {
    name: "United Arab Emirates",
    iso2: "AE",
    capital: "Abu Dhabi",
    phone: "+971",
    emergencyNumber: "999",
  },
  {
    name: "United Kingdom",
    iso2: "GB",
    capital: "London",
    phone: "+44",
    emergencyNumber: "999",
  },
  {
    name: "United States of America",
    iso2: "US",
    capital: "Washington, D.C.",
    phone: "+1",
    emergencyNumber: "911",
  },
  {
    name: "Uruguay",
    iso2: "UY",
    capital: "Montevideo",
    phone: "+598",
    emergencyNumber: "911",
  },
  {
    name: "Uzbekistan",
    iso2: "UZ",
    capital: "Tashkent",
    phone: "+998",
    emergencyNumber: "102",
  },
  {
    name: "Vanuatu",
    iso2: "VU",
    capital: "Port Vila",
    phone: "+678",
    emergencyNumber: "112",
  },
  {
    name: "Venezuela",
    iso2: "VE",
    capital: "Caracas",
    phone: "+58",
    emergencyNumber: "911",
  },
  {
    name: "Vietnam",
    iso2: "VN",
    capital: "Hanoi",
    phone: "+84",
    emergencyNumber: "113",
  },
  {
    name: "Yemen",
    iso2: "YE",
    capital: "Sanaa",
    phone: "+967",
    emergencyNumber: "199",
  },
  {
    name: "Zambia",
    iso2: "ZM",
    capital: "Lusaka",
    phone: "+260",
    emergencyNumber: "991",
  },
  {
    name: "Zimbabwe",
    iso2: "ZW",
    capital: "Harare",
    phone: "+263",
    emergencyNumber: "999",
  },
];
