export const Currencies =  [
  "USD US Dollar",
  "EUR Euro",
  "GBP British Pound",
  "CAD Canadian Dollar",
  "AUD Australian Dollar",
  "JPY Japanese Yen",
  "INR Indian Rupee",
  "NZD New Zealand Dollar",
  "CHF Swiss Franc",
  "ZAR South African Rand",
  "RUB Russian Ruble",
  "BGN Bulgarian Lev",
  "SGD Singapore Dollar",
  "HKD Hong Kong Dollar",
  "SEK Swedish Krona",
  "THB Thai Baht",
  "HUF Hungarian Forint",
  "CNY Chinese Yuan Renminbi",
  "NOK Norwegian Krone",
  "MXN Mexican Peso",
  "DKK Danish Krone",
  "MYR Malaysian Ringgit",
  "PLN Polish Zloty",
  "BRL Brazilian Real",
  "PHP Philippine Peso",
  "IDR Indonesian Rupiah",
  "CZK Czech Koruna",
  "AED Emirati Dirham",
  "TWD Taiwan New Dollar",
  "KRW South Korean Won",
  "ILS Israeli Shekel",
  "ARS Argentine Peso",
  "CLP Chilean Peso",
  "EGP Egyptian Pound",
  "TRY Turkish Lira",
  "RON Romanian Leu",
  "SAR Saudi Arabian Riyal",
  "PKR Pakistani Rupee",
  "COP Colombian Peso",
  "IQD Iraqi Dinar",
  "XAU Gold Ounce",
  "FJD Fijian Dollar",
  "KWD Kuwaiti Dinar",
  "BAM Bosnian Convertible Mark",
  "ISK Icelandic Krona",
  "MAD Moroccan Dirham",
  "VND Vietnamese Dong",
  "JMD Jamaican Dollar",
  "JOD Jordanian Dinar",
  "DOP Dominican Peso",
  "PEN Peruvian Sol",
  "CRC Costa Rican Colon",
  "BHD Bahraini Dinar",
  "BDT Bangladeshi Taka",
  "DZD Algerian Dinar",
  "KES Kenyan Shilling",
  "XAG Silver Ounce",
  "LKR Sri Lankan Rupee",
  "OMR Omani Rial",
  "QAR Qatari Riyal",
  "XOF CFA Franc",
  "IRR Iranian Rial",
  "XCD East Caribbean Dollar",
  "TND Tunisian Dinar",
  "TTD Trinidadian Dollar",
  "XPF CFP Franc",
  "EEK Estonian Kroon",
  "ZMK Zambian Kwacha",
  "ZMW Zambian Kwacha",
  "BBD Barbadian or Bajan Dollar",
  "NGN Nigerian Naira",
  "LBP Lebanese Pound",
  "XAF Central African CFA Franc BEAC",
  "MUR Mauritian Rupee",
  "XPT Platinum Ounce",
  "BSD Bahamian Dollar",
  "ALL Albanian Lek",
  "UYU Uruguayan Peso",
  "BMD Bermudian Dollar",
  "LVL Latvian Lat",
  "UAH Ukrainian Hryvnia",
  "GTQ Guatemalan Quetzal",
  "XDR IMF Special Drawing Rights",
  "BWP Botswana Pula",
  "BOB Bolivian Bolíviano",
  "CUP Cuban Peso",
  "PYG Paraguayan Guarani",
  "HNL Honduran Lempira",
  "LTL Lithuanian Litas",
  "NIO Nicaraguan Cordoba",
  "RSD Serbian Dinar",
  "NPR Nepalese Rupee",
  "HTG Haitian Gourde",
  "PAB Panamanian Balboa",
  "SVC Salvadoran Colon",
  "GYD Guyanese Dollar",
  "KYD Caymanian Dollar",
  "TZS Tanzanian Shilling",
  "CNH Chinese Yuan Renminbi Offshore",
  "CVE Cape Verdean Escudo",
  "FKP Falkland Island Pound",
  "ANG Dutch Guilder",
  "UGX Ugandan Shilling",
  "MGA Malagasy Ariary",
  "GEL Georgian Lari",
  "ETB Ethiopian Birr",
  "MDL Moldovan Leu",
  "VUV Ni-Vanuatu Vatu",
  "SYP Syrian Pound",
  "BND Bruneian Dollar",
  "KHR Cambodian Riel",
  "NAD Namibian Dollar",
  "MKD Macedonian Denar",
  "AOA Angolan Kwanza",
  "PGK Papua New Guinean Kina",
  "MMK Burmese Kyat",
  "KZT Kazakhstani Tenge",
  "MOP Macau Pataca",
  "MZN Mozambican Metical",
  "LYD Libyan Dinar",
  "SLE Sierra Leonean Leone",
  "SLL Sierra Leonean Leone",
  "GNF Guinean Franc",
  "BYN Belarusian Ruble",
  "BYR Belarusian Ruble",
  "GMD Gambian Dalasi",
  "AWG Aruban or Dutch Guilder",
  "AMD Armenian Dram",
  "YER Yemeni Rial",
  "LAK Lao Kip",
  "WST Samoan Tala",
  "MWK Malawian Kwacha",
  "KPW North Korean Won",
  "BIF Burundian Franc",
  "DJF Djiboutian Franc",
  "MNT Mongolian Tughrik",
  "UZS Uzbekistani Som",
  "TOP Tongan Pa'anga",
  "SCR Seychellois Rupee",
  "KGS Kyrgyzstani Som",
  "BTN Bhutanese Ngultrum",
  "SBD Solomon Islander Dollar",
  "GIP Gibraltar Pound",
  "RWF Rwandan Franc",
  "CDF Congolese Franc",
  "MVR Maldivian Rufiyaa",
  "MRU Mauritanian Ouguiya",
  "ERN Eritrean Nakfa",
  "SOS Somali Shilling",
  "SZL Swazi Lilangeni",
  "TJS Tajikistani Somoni",
  "LRD Liberian Dollar",
  "LSL Basotho Loti",
  "SHP Saint Helenian Pound",
  "STN Sao Tomean Dobra",
  "KMF Comorian Franc",
  "SPL Seborgan Luigino",
  "TMT Turkmenistani Manat",
  "SRD Surinamese Dollar",
  "IMP Isle of Man Pound",
  "JEP Jersey Pound",
  "TVD Tuvaluan Dollar",
  "GGP Guernsey Pound",
  "AFN Afghan Afghani",
  "AZN Azerbaijan Manat",
  "BZD Belizean Dollar",
  "CUC Cuban Convertible Peso",
  "GHS Ghanaian Cedi",
  "SDG Sudanese Pound",
  "VES Venezuelan Bolívar",
  "XPD Palladium Ounce",
  "BTC Bitcoin",
  "ADA Cardano",
  "BCH Bitcoin Cash",
  "DOGE Dogecoin",
  "DOT Polkadot",
  "ETH Ethereum",
  "LINK Chainlink",
  "LTC Litecoin",
  "LUNA Terra",
  "UNI Uniswap",
  "XLM Stellar Lumen",
  "XRP Ripple",
  "ZWG Zimbabwean Dollar",
  "HRK Croatian Kuna (obsolete)",
  "ZWD Zimbabwean Dollar (obsolete)",
  "VEF Venezuelan Bolívar (obsolete)",
  "ATS Austrian Schilling (obsolete)",
  "AZM Azerbaijani Manat (obsolete)",
  "BEF Belgian Franc (obsolete)",
  "CYP Cypriot Pound (obsolete)",
  "DEM German Deutsche Mark (obsolete)",
  "ESP Spanish Peseta (obsolete)",
  "FIM Finnish Markka (obsolete)",
  "FRF French Franc (obsolete)",
  "GHC Ghanaian Cedi (obsolete)",
  "GRD Greek Drachma (obsolete)",
  "IEP Irish Pound (obsolete)",
  "ITL Italian Lira (obsolete)",
  "LUF Luxembourg Franc (obsolete)",
  "MGF Malagasy Franc (obsolete)",
  "MRO Mauritanian Ouguiya (obsolete)",
  "MTL Maltese Lira (obsolete)",
  "MZM Mozambican Metical (obsolete)",
  "NLG Dutch Guilder (obsolete)",
  "PTE Portuguese Escudo (obsolete)",
  "ROL Romanian Leu (obsolete)",
  "SDD Sudanese Dinar (obsolete)",
  "SIT Slovenian Tolar (obsolete)",
  "SKK Slovak Koruna (obsolete)",
  "SRG Surinamese Guilder (obsolete)",
  "STD Sao Tomean Dobra (obsolete)",
  "TMM Turkmenistani Manat (obsolete)",
  "TRL Turkish Lira (obsolete)",
  "VAL Vatican City Lira (obsolete)",
  "VEB Venezuelan Bolívar (obsolete)",
  "XEU European Currency Unit (obsolete)",
  "ZWL Zimbabwean Dollar (obsolete)"
]