import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../styles/theme";

export const styles = StyleSheet.create({
  addActivityWrapper: {
    flex: 1,
    marginTop: 20,
  },
  addActivityFiles: {
    backgroundColor: "#fff",
    borderRadius: 15,
    width: "100%",
    paddingHorizontal: 15,
    paddingVertical: 20,
    marginTop: 15,
    flexDirection: "row",
    alignItems: "center",
  },
  addActivityFilesLabel: {
    fontSize: 14,
    color: COLORS.black,
    fontWeight: "600",
    marginLeft: 10,
  },
  inputItem: {
    marginLeft: 10,
    width: "100%",
    height: 40,
    fontSize: 16,
    color: COLORS.black,
    fontWeight: "600",
  },
  addActivityFromToDateBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
  },
  addActivityExpenses: {
    backgroundColor: "#fff",
    borderRadius: 15,
    width: "48%",
    flexDirection: "column",
    padding: 15,
    alignItems: "flex-start",
  },
  addActivityExpensesLabel: {
    marginTop: 15,
    fontSize: 14,
    color: COLORS.black,
    fontWeight: "600",
  },
  addActivitySeat: {
    backgroundColor: "#fff",
    borderRadius: 15,
    width: "48%",
    padding: 15,
    flexDirection: "column",
    marginBottom: 0,
    alignItems: "flex-start",
  },
  addActivitySeatLabel: {
    marginTop: 15,
    fontSize: 14,
    color: COLORS.black,
    fontWeight: "600",
  },
  addActivityOthers: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 15,
  },
  addActivityFromToDateLabel: {
    marginTop: 20,
    fontSize: 14,
    color: COLORS.black,
    fontWeight: "600",
  },
  addActivityFromToDate: {
    backgroundColor: "#fff",
    borderRadius: 15,
    width: "48%",
    padding: 15,
  },
  addActivityFromToBox: {
    backgroundColor: "#fff",
    borderRadius: 15,
    marginTop: 25,
    position: "relative",
  },
  fromToLine: {
    position: "absolute",
    borderWidth: 1,
    borderStyle: "dashed",
    height: 50,
    top: 55,
    left: 24,
    borderColor: "#ccc",
  },
  addActivityFromToIcon: {
    marginRight: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  addActivityFromToLabel: {
    fontSize: 14,
    color: COLORS.black,
    fontWeight: "600",
    marginLeft: 0,
  },
  addActivityFromToValue: {
    marginTop: 5,
    color: "#808080",
    fontSize: 14,
  },
  addActivitySeatLabelValue: {
    marginTop: 5,
    color: "#808080",
    fontSize: 14,
  },
  addActivityExpensesLabelValue: {
    marginTop: 5,
    color: "#808080",
    fontSize: 14,
  },
  AddActivityFromTo: {
    paddingHorizontal: 15,
    paddingVertical: 20,
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  addActivityFromToIn: {
    flexDirection: "row",
    alignItems: "center",
  },
  addActivityFromToText: {
    marginLeft: 10,
  },
  addActivityTitleInput: {
    color: COLORS.black,
    height: 40,
    fontSize: 20,
    width: "100%",
    fontWeight: "600",
  },
  addActivityHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  addActivityHeaderIcon: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    borderRadius: 100,
    marginRight: 15,
  },
  pagerView: {
    flex: 1,
    height: SIZES.height - 200,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.black,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.black,
  },
  saveButton: {
    padding: 10,
    marginTop: -10,
    marginRight: -10,
    width: 100,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  activityTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backToPrevSlideText: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.black,
  },
  backToPrevSlide: {
    padding: 10,
    marginTop: -10,
    marginLeft: -10,
    width: 100,
  },
  modalHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    position: "relative",
  },
  icon: {
    width: 35,
    height: 35,
    borderRadius: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  activityLabel: {
    color: "#A6A6A6",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 20,
  },
  activity: {
    width: "48.5%",
    backgroundColor: "#FFF",
    padding: 15,
    marginBottom: 10,
    borderRadius: 15,
  },
  activities: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    marginTop: 25,
  },
  closeButton: {},
  title: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.black,
  },
  subTitle: {
    fontSize: 16,
    marginTop: 10,
  },
  switchers: {
    marginTop: 25,
  },
  switcher: {
    backgroundColor: COLORS.white,
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginBottom: 15,
    borderRadius: 10,
  },
  switcherLabel: {
    color: COLORS.black,
    fontSize: 16,
    fontWeight: "500",
  },
  active: {
    backgroundColor: COLORS.primaryDark,
  },
  activeText: {
    color: COLORS.white,
  },
  wrapper: {
    paddingHorizontal: 15,
    paddingTop: 15,
  },
});
