import { StyleSheet } from "react-native";

import { COLORS, SIZES } from "../../styles/theme";

export const tripDetailStyles = StyleSheet.create({
  actionTitle: {
    color: COLORS.gray,
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
  },
  addActivityButton: {
    alignItems: "center",
    backgroundColor: COLORS.black,
    borderRadius: 50,
    bottom: 25,
    display: "flex",
    height: 50,
    justifyContent: "center",
    position: "absolute",
    right: 15,
    width: 50,
    zIndex: 2,
    ...COLORS.shadow,
  },
  addActivityButtonItem: {
    backgroundColor: "#000",
    borderRadius: 50,
    marginTop: 25,
    padding: 12,
    width: 200,
  },
  addActivityButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  addUserButton: {
    alignItems: "center",
    backgroundColor: "#8e8e8e",
    borderRadius: 50,
    height: 25,
    justifyContent: "center",
    left: -10,
    position: "relative",
    top: 0,
    width: 25,
    zIndex: 2,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 50,
    display: "flex",
    height: 35,
    justifyContent: "center",
    left: 20,
    position: "absolute",
    top: 55,
    width: 35,
  },
  bottomActions: {
    alignItems: "flex-end",
    flexDirection: "row",
  },
  bottomRight: {
    alignItems: "center",
    flexDirection: "row",
  },
  centeredView: {
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    flex: 1,
    justifyContent: "center",
    marginTop: 0,
  },
  checkedIn: {
    opacity: 0.6,
    // backgroundColor: "#f2f7ff"
  },
  checkinButton: {
    alignItems: "center",
    backgroundColor: "#fafafa",
    borderRadius: 6,
    flexDirection: "column",
    marginLeft: -2,
    paddingHorizontal: 7,
    paddingVertical: 5,
    position: "relative",
    width: 65,
    zIndex: 2,
  },
  checkinButtonText: {
    color: COLORS.gray,
    fontSize: 13,
    fontWeight: "600",
  },
  circleItem: {
    left: -11,
    marginTop: -15,
    position: "absolute",
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#DBDBDB",
    borderRadius: 50,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  customTab: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingVertical: 0,
    position: "relative",
  },
  customTabLabel: {
    fontSize: 14,
    fontWeight: "600",
    marginTop: 0,
  },
  descText: {
    color: "#707579",
    fontSize: 12,
    fontWeight: "500",
  },
  documentItem: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 15,
    flexDirection: "row",
    height: 60,
    justifyContent: "space-between",
    marginBottom: 15,
    padding: 15,
  },
  documentItemLeft: {
    alignItems: "center",
    flexDirection: "row",
  },
  documentItemOptions: {
    marginRight: -8,
    padding: 8,
  },
  documentItemTitle: {
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 8,
  },
  editButton: {
    alignItems: "center",
    borderRadius: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: -8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  editButtonText: {
    color: COLORS.black,
    fontSize: 12,
    marginLeft: 5,
  },
  h2: {
    color: COLORS.black,
    fontSize: 22,
    fontWeight: "bold",
  },
  iconWrapper: {
    alignItems: "center",
    height: 18,
    justifyContent: "center",
    marginBottom: 0,
  },
  imageOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    height: "100%",
    justifyContent: "center",
    left: 0,
    position: "absolute",
    top: 0,
    width: "100%",
  },
  imagesWrapper: {
    flexDirection: "row",
    width: "100%",
  },
  invitationBox: {
    flexDirection: "row",
    maxWidth: 120,
    position: "relative",
  },
  invitationBoxTexts: {
    flexDirection: "column",
    marginLeft: 10,
  },
  invitationStatus: {
    color: COLORS.gray,
    fontSize: 12,
    marginTop: 3,
  },
  inviteBox: {
    alignItems: "center",
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    overflow: "hidden",
    paddingHorizontal: 15,
    paddingTop: 15,
  },
  inviteBoxInput: {
    backgroundColor: "#fafafa",
    borderBottomStartRadius: 10,
    borderTopLeftRadius: 10,
    color: COLORS.black,
    flex: 1,
    height: 50,
    paddingLeft: 15,
  },
  inviteButton: {
    alignItems: "center",
    backgroundColor: COLORS.primaryDark,
    borderBottomEndRadius: 10,
    borderTopRightRadius: 10,
    height: 50,
    justifyContent: "center",
    paddingHorizontal: 25,
  },
  inviteButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  inviteOne: {
    borderRadius: 50,
    height: 25,
    width: 25,
  },
  inviteTwo: {
    borderColor: "#fff",
    borderRadius: 50,
    borderWidth: 1,
    height: 25,
    left: -10,
    position: "relative",
    top: 0,
    width: 25,
    zIndex: 2,
  },
  invitedList: {
    marginTop: 15,
    // flex: 1,
    paddingHorizontal: 15,
  },
  invitedListItem: {
    alignItems: "center",
    backgroundColor: COLORS.lightGray,
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
    padding: 15,
    width: "100%",
  },
  invitedUserImage: {
    borderRadius: 50,
    minHeight: 25,
    minWidth: 25,
    width: 25,
  },
  invitedUserName: {
    color: COLORS.black,
    fontSize: 14,
    fontWeight: "600",
  },
  lastImage: {
    borderRadius: 10,
    height: 110,
    overflow: "hidden",
    position: "relative",
    width: (SIZES.width - 48) / 3,
  },
  leftSide: {},
  lfSide: {
    alignItems: "center",
    flexDirection: "row",
  },
  mainImage: {
    borderRadius: 10,
    height: 110,
    marginRight: 8,
    width: (SIZES.width - 90) / 3,
  },
  map: {
    height: 130,
  },
  mapButton: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 50,
    display: "flex",
    height: 35,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    top: 55,
    width: 35,
  },
  mapHeaderContainer: {
    position: "relative",
  },
  modalViewCenter: {
    backgroundColor: "#F2F2F7",
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderRadius: 15,
    height: "100%",
    width: "100%",
  },
  modalViewWrapper: {
    alignItems: "flex-end",
    flex: 1,
    justifyContent: "flex-end",
  },
  noActivitiesWrapper: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 130,
  },
  noActivitiesWrapperTitle: {
    fontSize: 16,
    fontWeight: "600",
  },
  noResultWrapper: {
    alignItems: "center",
    flex: 1,
    height: 250,
    justifyContent: "center",
    marginTop: 45,
    paddingHorizontal: 15,
    textAlign: "center",
  },
  noResultWrapperText: {
    color: COLORS.darkgray,
    fontSize: 16,
    lineHeight: 20,
    marginTop: 25,
    maxWidth: "80%",
    textAlign: "center",
  },
  otherUsers: {
    alignItems: "center",
    backgroundColor: "#8e8e8e",
    borderColor: "#fff",
    borderRadius: 50,
    borderWidth: 1,
    height: 25,
    justifyContent: "center",
    left: -20,
    position: "relative",
    top: 0,
    width: 25,
    zIndex: 2,
  },
  otherUsersText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "600",
  },
  pinIcon: {
    alignItems: "center",
    display: "flex",
    justifyContent: "center",
    left: -33,
    position: "absolute",
  },
  ratingLabel: {
    alignItems: "center",
    flexDirection: "row",
  },
  ratingText: {
    color: COLORS.darkgray,
    fontSize: 13,
    fontWeight: "400",
    marginRight: 0,
  },
  rightSide: {
    alignItems: "flex-end",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  rowItemHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingBottom: 10,
    paddingHorizontal: 15,
    paddingTop: 0,
    width: "100%",
  },
  sightBottomActions: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 25,
    marginTop: 5,
    paddingHorizontal: 15,
    width: "100%",
  },
  sightDetails: {
    marginTop: 15,
    width: "100%",
  },
  sightItem: {
    backgroundColor: "#fff",
    borderRadius: 10,
    flex: 1,
    flexDirection: "column",
    flexWrap: "wrap",
    height: 150,
    marginLeft: 0,
    minHeight: 110,
    padding: 15,
    paddingVertical: 20,
    position: "relative",
    // borderWidth: 1,
    // borderColor: "#fff"
  },
  sightRight: {
    marginLeft: 15,
  },
  sightRightActions: {
    alignItems: "center",
    flexDirection: "row",
  },
  sightRightActionsButton: {
    alignItems: "center",
    borderRadius: 6,
    display: "flex",
    justifyContent: "center",
    marginLeft: 6,
    paddingHorizontal: 3,
    paddingVertical: 0,
  },
  sightRightActionsButtonText: {
    color: COLORS.gray,
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 5,
  },
  sightTitle: {
    color: COLORS.black,
    fontSize: 18,
    fontWeight: "600",
  },
  sightType: {
    color: COLORS.darkgray,
    fontSize: 13,
    fontWeight: "400",
    marginLeft: 3,
  },
  smallCircle: {
    backgroundColor: COLORS.primary,
    borderColor: "#fff",
    borderRadius: 100,
    borderWidth: 3,
    height: 15,
    position: "absolute",
    width: 15,
  },
  tripDestination: {
    color: COLORS.darkgray,
    fontSize: 14,
    fontWeight: "500",
    marginTop: 10,
  },
  tripDetailsHeader: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: -25,
    paddingHorizontal: 0,
    paddingTop: 20,
  },
  tripName: {
    color: COLORS.black,
    fontSize: 22,
    fontWeight: "bold",
  },
  tripType: {
    color: COLORS.black,
    fontSize: 14,
    fontWeight: "500",
  },
  uploadButton: {
    alignItems: "center",
    backgroundColor: COLORS.primaryDark,
    borderRadius: 50,
    flexDirection: "row",
    height: 50,
    marginTop: 25,
    paddingHorizontal: 15,
  },
  uploadButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  verticalLine: {
    borderStyle: "solid",
    borderColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
    // borderLeftWidth: 2,
    position: "absolute",
    left: 0,
    opacity: 1,
  },
});
