import { StyleSheet } from "react-native";
import { COLORS, SIZES } from "../../styles/theme";

export const tripDetailStyles = StyleSheet.create({
  noActivitiesWrapper: {
    marginTop: 70,
    justifyContent: "center",
    alignItems: "center",
  },
  noActivitiesWrapperTitle: {
    fontSize: 16,
    fontWeight: "600"
  },
  circleItem: {
    position: "absolute",
    marginTop: -15,
    left: -11
  },
  smallCircle: {
    width: 15,
    height: 15,
    backgroundColor: COLORS.primary,
    borderRadius: 100,
    borderColor: "#fff",
    borderWidth: 3,
    position: "absolute",
  },
  verticalLine: {
    borderStyle: "solid",
    borderColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
    // borderLeftWidth: 2,
    position: "absolute",
    left: 0,
    opacity: 1
  },
  addActivityButtonItem :{
    backgroundColor: "#000",
    borderRadius: 50,
    padding: 12,
    width: 200,
    marginTop: 25
  },
  addActivityButtonText: {
    color: "#fff",
    fontWeight: "500",
    textAlign: "center",
    fontSize: 14
  },
    uploadButton: {
      backgroundColor: COLORS.primaryDark,
      flexDirection: "row",
      alignItems: "center",
      borderRadius: 50,
      paddingHorizontal: 15,
      marginTop: 25,
      height: 50,
    },
    modalViewWrapper: {
      flex: 1,
      justifyContent: "flex-end",
      alignItems: "flex-end",
    },
    modalViewCenter: {
      backgroundColor: "#F2F2F7",
      borderRadius: 15,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      width: "100%",
      height: "100%",
    },
    uploadButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "500",
    },
    documentItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      height: 60,
      backgroundColor: "#fff",
      borderRadius: 15,
      padding: 15,
      marginBottom: 15,
    },
    documentItemLeft: {
      flexDirection: "row",
      alignItems: "center",
    },
    documentItemTitle: {
      marginLeft: 8,
      fontSize: 16,
      fontWeight: "500",
    },
    documentItemOptions: {
      padding: 8,
      marginRight: -8,
    },
    rowItemHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 15,
      paddingTop: 15,
      paddingBottom: 10,
      width: "100%"
    },
    checkedIn: {
      opacity: 0.6,
      // backgroundColor: "#f2f7ff"
    },
    sightRightActionsButtonText: {
      fontSize: 12,
      marginLeft: 5,
      fontWeight: "500",
      color: COLORS.gray,
    },
    invitationStatus: {
      fontSize: 12,
      color: COLORS.gray,
      marginTop: 3,
    },
    invitationBoxTexts: {
      flexDirection: "column",
      marginLeft: 10,
    },
    noResultWrapper: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      height: 250,
      textAlign: "center",
      paddingHorizontal: 15,
      marginTop: 45,
    },
    noResultWrapperText: {
      fontSize: 16,
      color: COLORS.darkgray,
      marginTop: 25,
      textAlign: "center",
      lineHeight: 20,
      maxWidth: "80%",
    },
    invitedList: {
      marginTop: 15,
      // flex: 1,
      paddingHorizontal: 15,
    },
    invitedListItem: {
      width: "100%",
      marginBottom: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: COLORS.lightGray,
      padding: 15,
      borderRadius: 10,
    },
    lfSide: {
      flexDirection: "row",
      alignItems: "center",
    },
    invitedUserImage: {
      minWidth: 25,
      minHeight: 25,
      width: 25,
      borderRadius: 50,
    },
    closeButton: {
      backgroundColor: "#DBDBDB",
      width: 30,
      height: 30,
      borderRadius: 50,
      justifyContent: "center",
      alignItems: "center",
    },
    invitedUserName: {
      fontSize: 14,
      color: COLORS.black,
      fontWeight: "600",
    },
    inviteBox: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderTopRightRadius: 10,
      borderTopLeftRadius: 10,
      overflow: "hidden",
      paddingHorizontal: 15,
      paddingTop: 15,
    },
    inviteBoxInput: {
      height: 50,
      backgroundColor: "#fafafa",
      flex: 1,
      paddingLeft: 15,
      color: COLORS.black,
      borderTopLeftRadius: 10,
      borderBottomStartRadius: 10,
    },
    centeredView: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 0,
      backgroundColor: "rgba(0, 0, 0, 0.2)",
    },
    inviteButton: {
      paddingHorizontal: 25,
      backgroundColor: COLORS.primaryDark,
      height: 50,
      alignItems: "center",
      justifyContent: "center",
      borderTopRightRadius: 10,
      borderBottomEndRadius: 10,
    },
    iconWrapper: {
      height: 16,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 3
    },
    inviteButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
    },
    h2: {
      fontSize: 22,
      color: COLORS.black,
      fontWeight: "bold",
    },
    addActivityButton: {
      width: 50,
      height: 50,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      position: "absolute",
      bottom: 25,
      right: 15,
      backgroundColor: COLORS.primary,
      zIndex: 2,
      borderRadius: 50,
      ...COLORS.shadow,
    },
    mapHeaderContainer: {
      position: "relative",
    },
    sightDetails: {
      width: "100%",
      marginTop: 15,
    },
    sightRightActionsButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      marginLeft: 6,
      borderRadius: 6,
      paddingVertical: 0,
      paddingHorizontal: 3,
    },
    actionTitle: {
      fontSize: 10,
      color: COLORS.gray,
      fontWeight: "600",
    },
    sightRightActions: {
      flexDirection: "row",
      alignItems: "center",
    },
    checkinButtonText: {
      fontSize: 11,
      color: COLORS.gray,
      fontWeight: "600"
    },
    checkinButton: {
      flexDirection: "column",
      alignItems: "center",
      borderRadius: 6,
      paddingVertical: 5,
      backgroundColor: "#fafafa",
      paddingHorizontal: 7,
      width: 65,
      position: "relative",
      zIndex: 2,
      marginLeft: -2
    },
    sightTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: COLORS.black,
    },
    ratingLabel: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 8,
    },
    ratingText: {
      fontWeight: "400",
      color: COLORS.darkgray,
      fontSize: 12,
      marginRight: 2,
    },
    sightType: {
      fontWeight: "400",
      color: COLORS.darkgray,
      fontSize: 12,
      marginLeft: 3,
    },
    sightRight: {
      marginLeft: 15,
    },
    sightItem: {
      backgroundColor: "#fff",
      minHeight: 110,
      flex: 1,
      borderRadius: 10,
      marginLeft: 0,
      padding: 15,
      paddingVertical: 20,
      flexDirection: "column",
      position: "relative",
      flexWrap: "wrap",
      height: 150,
      // borderWidth: 1,
      // borderColor: "#fff"
    },
    imagesWrapper: {
      flexDirection: "row",
      width: "100%",
    },
    pinIcon: {
      position: "absolute",
      left: -33,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
    sightBottomActions: {
      marginTop: 5,
      marginBottom: 25,
      width: "100%",
      justifyContent: "space-between",
      alignItems: "center",
      flexDirection: "row",
      paddingHorizontal: 15
    },
    addUserButton: {
      position: "relative",
      left: -10,
      zIndex: 2,
      top: 0,
      width: 25,
      height: 25,
      borderRadius: 50,
      backgroundColor: "#8e8e8e",
      alignItems: "center",
      justifyContent: "center",
    },
    invitationBox: {
      position: "relative",
      flexDirection: "row",
      maxWidth: 120,
    },
    bottomRight: {
      flexDirection: "row",
      alignItems: "center",
    },
    otherUsersText: {
      fontWeight: "600",
      color: "#fff",
      fontSize: 10,
    },
    otherUsers: {
      position: "relative",
      left: -20,
      zIndex: 2,
      top: 0,
      width: 25,
      height: 25,
      borderRadius: 50,
      backgroundColor: "#8e8e8e",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: "#fff",
    },
    inviteTwo: {
      position: "relative",
      left: -10,
      zIndex: 2,
      top: 0,
      width: 25,
      height: 25,
      borderRadius: 50,
      borderWidth: 1,
      borderColor: "#fff",
    },
    tripName: {
      fontSize: 22,
      fontWeight: "bold",
      color: COLORS.black,
    },
    bottomActions: {
      flexDirection: "row",
      alignItems: "flex-end",
    },
    rightSide: {
      flexDirection: "column",
      alignItems: "flex-end",
      justifyContent: "space-between",
    },
    mainImage: {
      width: (SIZES.width - 90 ) / 3,
      height: 110,
      borderRadius: 10,
      marginRight: 8,
    },
    tripType: {
      fontSize: 14,
      fontWeight: "500",
      color: COLORS.black,
    },
    imageOverlay: {
      position: "absolute",
      top: 0,
      left: 0,
      backgroundColor: "rgba(0,0,0,0.3)",
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center"
    },
    lastImage: {
      width: (SIZES.width - 48 ) / 3,
      height: 110,
              borderRadius: 10,
              overflow: "hidden",
              position: "relative",
    },
    descText: {
      fontSize: 12,
      fontWeight: "500",
      color: "#707579"
    },
    leftSide: {},
    tripDestination: {
      fontSize: 14,
      fontWeight: "500",
      color: COLORS.darkgray,
      marginTop: 10,
    },
    inviteOne: {
      width: 25,
      height: 25,
      borderRadius: 50,
    },
    editButton: {
      borderRadius: 10,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      paddingVertical: 8,
      paddingHorizontal: 10,
      marginTop: -8,
    },
    editButtonText: {
      fontSize: 12,
      color: COLORS.black,
      marginLeft: 5,
    },
    customTab: {
      flex: 1,
      position: "relative",
      justifyContent: "center",
      alignItems: "center",
      paddingVertical: 0,
    },
    tripDetailsHeader: {
      backgroundColor: "#fff",
      paddingHorizontal: 0,
      paddingTop: 20,
      marginTop: -25,
      borderTopRightRadius: 25,
      borderTopLeftRadius: 25,
      flexDirection: "row",
      justifyContent: "space-between",
      flexWrap: "wrap",
    },
    customTabLabel: {
      fontWeight: "600",
      marginTop: 0,
      fontSize: 14,
    },
    backButton: {
      position: "absolute",
      top: 55,
      left: 20,
      width: 35,
      height: 35,
      backgroundColor: "#fff",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 50,
    },
    mapButton: {
      position: "absolute",
      top: 55,
      right: 20,
      width: 35,
      height: 35,
      backgroundColor: "#fff",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 50,
    },
    map: {
      height: 130,
    },
  });